# Generated by Django 4.1.5 on 2023-08-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantiere', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
