# Generated by Django 4.1.5 on 2023-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esterni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantiere_Esterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantiere', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cantiere',
        ),
    ]
