# Generated by Django 4.1.5 on 2023-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0051_formazione_rullo_formazione_rullo_ck_and_more'),
        ('esterni', '0002_cantiere_esterno_delete_cantiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantiere_esterno',
            name='elenco_lavoratori',
            field=models.ManyToManyField(to='personale.lavoratore'),
        ),
    ]
