# Generated by Django 4.1.5 on 2023-08-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0020_alter_mezzo_inail_alter_mezzo_inail_ck'),
        ('esterni', '0003_cantiere_esterno_elenco_lavoratori'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantiere_esterno',
            name='elenco_mezzi',
            field=models.ManyToManyField(to='mezzi.mezzo'),
        ),
    ]
