# Generated by Django 4.1.5 on 2023-08-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esterni', '0004_cantiere_esterno_elenco_mezzi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cantiere_esterno',
            options={'ordering': ['cantiere'], 'verbose_name': 'Cantiere Esterno', 'verbose_name_plural': 'Cantieri Esterni'},
        ),
        migrations.AddField(
            model_name='cantiere_esterno',
            name='in_corso',
            field=models.BooleanField(default=True),
        ),
    ]
