# Generated by Django 4.1.5 on 2023-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0051_formazione_rullo_formazione_rullo_ck_and_more'),
        ('mezzi', '0020_alter_mezzo_inail_alter_mezzo_inail_ck'),
        ('esterni', '0006_alter_cantiere_esterno_elenco_lavoratori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantiere_esterno',
            name='elenco_lavoratori',
            field=models.ManyToManyField(blank=True, to='personale.lavoratore'),
        ),
        migrations.AlterField(
            model_name='cantiere_esterno',
            name='elenco_mezzi',
            field=models.ManyToManyField(blank=True, to='mezzi.mezzo'),
        ),
    ]
