# Generated by Django 4.1.5 on 2023-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0051_formazione_rullo_formazione_rullo_ck_and_more'),
        ('esterni', '0007_alter_cantiere_esterno_elenco_lavoratori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantiere_esterno',
            name='elenco_lavoratori2',
            field=models.ManyToManyField(blank=True, to='personale.formazione'),
        ),
    ]
