# Generated by Django 4.1.5 on 2023-08-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esterni', '0008_cantiere_esterno_elenco_lavoratori2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantiere_esterno',
            name='elenco_lavoratori2',
        ),
    ]
