# Generated by Django 4.0.2 on 2022-07-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipologia',
                'verbose_name_plural': 'Tipologie',
            },
        ),
        migrations.CreateModel(
            name='Attrezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('matricola', models.CharField(blank=True, max_length=20, null=True)),
                ('ce', models.BooleanField(default=False)),
                ('manuale', models.BooleanField(default=False)),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attrezzi.tipologia')),
            ],
            options={
                'verbose_name': 'Attrezzo',
                'verbose_name_plural': 'Attrezzi',
            },
        ),
    ]
