# Generated by Django 4.0.2 on 2022-07-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrezzi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attrezzo',
            old_name='nome',
            new_name='marca',
        ),
        migrations.AddField(
            model_name='attrezzo',
            name='faldone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attrezzo',
            name='modello',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
