# Generated by Django 4.0.2 on 2022-07-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrezzi', '0002_rename_nome_attrezzo_marca_attrezzo_faldone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipologia',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
