# Generated by Django 4.0.2 on 2022-09-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attrezzi', '0003_alter_tipologia_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attrezzo',
            options={'ordering': ['tipologia', 'marca', 'modello', 'matricola'], 'verbose_name': 'Attrezzo', 'verbose_name_plural': 'Attrezzi'},
        ),
        migrations.AlterModelOptions(
            name='tipologia',
            options={'ordering': ['nome'], 'verbose_name': 'Tipologia', 'verbose_name_plural': 'Tipologie'},
        ),
    ]
