# Generated by Django 4.1.5 on 2023-06-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrezzi', '0004_alter_attrezzo_options_alter_tipologia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipologia',
            name='faldone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
