# Generated by Django 4.1.5 on 2023-07-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attrezzi', '0005_tipologia_faldone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attrezzo',
            name='faldone',
        ),
    ]
