# Generated by Django 4.1.5 on 2025-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrezzi', '0006_remove_attrezzo_faldone'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrezzo',
            name='in_uso',
            field=models.BooleanField(default=True),
        ),
    ]
