# Generated by Django 4.0.2 on 2022-11-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese', models.CharField(blank=True, max_length=20, null=True)),
                ('corso', models.CharField(blank=True, max_length=3, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('argomento', models.CharField(blank=True, max_length=100, null=True)),
                ('docente', models.CharField(blank=True, max_length=20, null=True)),
                ('ore', models.CharField(blank=True, max_length=6, null=True)),
                ('persone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
