# Generated by Django 4.0.2 on 2022-11-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formazione',
            options={'ordering': ['mese', 'data', 'corso'], 'verbose_name': 'Formazione', 'verbose_name_plural': 'Formazioni'},
        ),
        migrations.AlterField(
            model_name='formazione',
            name='corso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='mese',
            field=models.CharField(blank=True, choices=[('01', 'Gennaio'), ('02', 'Febbraio'), ('03', 'Marzo'), ('04', 'Aprile'), ('05', 'Maggio'), ('06', 'Giugno'), ('07', 'Luglio'), ('08', 'Agosto'), ('09', 'Settembre'), ('10', 'Ottobre'), ('11', 'Novembre'), ('12', 'Dicembre'), ('s1', '1° Semestre'), ('s2', '2° Semestre')], max_length=20, null=True),
        ),
    ]
