# Generated by Django 4.0.2 on 2022-11-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0002_alter_formazione_options_alter_formazione_corso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formazione',
            options={'ordering': ['-mese', 'data', 'corso'], 'verbose_name': 'Formazione', 'verbose_name_plural': 'Formazioni'},
        ),
    ]
