# Generated by Django 4.1.5 on 2023-01-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0003_alter_formazione_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formazione',
            options={'ordering': ['-mese', '-data', '-corso'], 'verbose_name': 'Formazione', 'verbose_name_plural': 'Formazioni'},
        ),
    ]
