# Generated by Django 4.1.5 on 2023-03-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0004_alter_formazione_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formazione',
            options={'ordering': ['-data', '-corso'], 'verbose_name': 'Formazione', 'verbose_name_plural': 'Formazioni'},
        ),
        migrations.AlterField(
            model_name='formazione',
            name='docente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
