# Generated by Django 4.1.5 on 2023-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0005_alter_formazione_options_alter_formazione_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_Conformita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('emittente', models.CharField(blank=True, choices=[('sogein', 'CSE SOGEIN'), ('scc', 'CSE SCC'), ('a_scc', 'Assistente CSE SCC'), ('aspp', 'ASPP'), ('hse eni', 'HSE ENI')], max_length=10, null=True)),
                ('area', models.CharField(blank=True, choices=[('sic', 'Sicurezza')], default='sic', max_length=10, null=True)),
                ('tipologia', models.CharField(blank=True, choices=[('nc', 'NC')], default='nc', max_length=10, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('trattamento', models.TextField(blank=True, null=True)),
                ('causa', models.TextField(blank=True, null=True)),
                ('azione_correttiva', models.TextField(blank=True, null=True)),
                ('responsabile_trattamento', models.CharField(blank=True, choices=[('aspp', 'ASPP')], default='aspp', max_length=10, null=True)),
                ('data_completamento', models.DateField(blank=True, null=True)),
                ('data_verifica', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
