# Generated by Django 4.1.5 on 2023-08-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0006_non_conformita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='non_conformita',
            options={'ordering': ['data'], 'verbose_name': 'Non Conformità', 'verbose_name_plural': 'Non Conformità'},
        ),
    ]
