# Generated by Django 4.1.5 on 2023-11-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0007_alter_non_conformita_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='non_conformita',
            options={'ordering': ['-data'], 'verbose_name': 'Non Conformità', 'verbose_name_plural': 'Non Conformità'},
        ),
        migrations.AlterField(
            model_name='non_conformita',
            name='emittente',
            field=models.CharField(blank=True, choices=[('sogein', 'CSE SOGEIN'), ('scc', 'CSE SCC'), ('a_scc', 'Assistente CSE SCC'), ('aspp', 'ASPP'), ('hse eni', 'HSE ENI'), ('a_hse_scc', 'Assistente HSE SCC')], max_length=10, null=True),
        ),
    ]
