# Generated by Django 4.1.5 on 2023-11-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0060_alter_idoneita_dpi_respiratori'),
        ('sgi', '0008_alter_non_conformita_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPI2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consegna', models.DateField(blank=True, default=None, null=True)),
                ('elmetto', models.DateField(blank=True, default=None, null=True)),
                ('elmetto_df', models.DateField(blank=True, default=None, null=True)),
                ('rilevatore', models.DateField(blank=True, default=None, null=True)),
                ('maschera', models.DateField(blank=True, default=None, null=True)),
                ('lavoratore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.lavoratore')),
            ],
            options={
                'verbose_name': 'Consegna DPI',
                'verbose_name_plural': 'Consegne DPI',
                'ordering': ['lavoratore'],
            },
        ),
    ]
