# Generated by Django 4.1.5 on 2023-12-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0009_dpi2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CassettaPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(blank=True, choices=[(0, 'Dismessa'), (-1, 'Da reintegrare'), (1, 'Ok')], max_length=10, null=True)),
                ('numero', models.CharField(max_length=10)),
                ('ubicazione', models.CharField(max_length=30)),
                ('allegato', models.CharField(blank=True, choices=[(1, 1), (2, 2)], max_length=10, null=True)),
                ('messa_in_servizio', models.DateField(blank=True, null=True)),
                ('dismissione', models.DateField(blank=True, null=True)),
                ('scadenza', models.DateField(blank=True, null=True)),
                ('ultima_verifica', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificaCassettaPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_verifica', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('cassetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgi.cassettaps')),
            ],
        ),
    ]
