# Generated by Django 4.1.5 on 2023-12-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0010_cassettaps_verificacassettaps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cassettaps',
            options={'ordering': ['numero'], 'verbose_name': 'Cassetta PS', 'verbose_name_plural': 'Cassette PS'},
        ),
        migrations.AlterModelOptions(
            name='verificacassettaps',
            options={'ordering': ['data_verifica', 'cassetta'], 'verbose_name': 'Verifica cassetta PS', 'verbose_name_plural': 'Verifiche cassette PS'},
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='operazione',
            field=models.CharField(blank=True, choices=[('ok', 'Verificata'), ('rei', 'Reintegrato'), ('dis', 'Dismessa')], max_length=10, null=True),
        ),
    ]
