# Generated by Django 4.1.5 on 2023-12-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0011_alter_cassettaps_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacassettaps',
            name='data_scadenza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cassettaps',
            name='allegato',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cassettaps',
            name='stato',
            field=models.CharField(blank=True, choices=[('0', 'Dismessa'), ('-1', 'Da reintegrare'), ('1', 'Ok')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='verificacassettaps',
            name='operazione',
            field=models.CharField(blank=True, choices=[('ok', 'Verificata'), ('no', 'Verificata da reintegrata'), ('rei', 'Reintegrata'), ('dis', 'Dismessa')], max_length=10, null=True),
        ),
    ]
