# Generated by Django 4.1.5 on 2023-12-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0012_verificacassettaps_data_scadenza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cassettaps',
            name='scadenza',
        ),
        migrations.RemoveField(
            model_name='cassettaps',
            name='ultima_verifica',
        ),
        migrations.AlterField(
            model_name='cassettaps',
            name='allegato',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], default='2', max_length=10, null=True),
        ),
    ]
