# Generated by Django 4.1.5 on 2023-12-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0013_remove_cassettaps_scadenza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassettaps',
            name='scadenza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cassettaps',
            name='ultima_verifica',
            field=models.DateField(blank=True, null=True),
        ),
    ]
