# Generated by Django 4.1.5 on 2023-12-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0014_cassettaps_scadenza_cassettaps_ultima_verifica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificacassettaps',
            options={'ordering': ['-data_verifica', 'cassetta'], 'verbose_name': 'Verifica cassetta PS', 'verbose_name_plural': 'Verifiche cassette PS'},
        ),
        migrations.AlterField(
            model_name='verificacassettaps',
            name='operazione',
            field=models.CharField(blank=True, choices=[('ok', 'Verificata'), ('no', 'Da reintegrare'), ('rei', 'Reintegrata'), ('dis', 'Dismessa')], max_length=10, null=True),
        ),
    ]
