# Generated by Django 4.1.5 on 2023-12-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0015_alter_verificacassettaps_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassettaps',
            name='ubicazione',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
