# Generated by Django 4.1.5 on 2023-12-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0016_alter_cassettaps_ubicazione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificacassettaps',
            options={'ordering': ['cassetta', '-data_verifica'], 'verbose_name': 'Verifica cassetta PS', 'verbose_name_plural': 'Verifiche cassette PS'},
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='materiale_da_integrare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='materiale_integrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificacassettaps',
            name='operazione',
            field=models.CharField(blank=True, choices=[('ok', 'Verificata'), ('no', 'Da reintegrare'), ('rei', 'Reintegrata'), ('dis', 'Dismessa'), ('ms', 'Messa in servizio')], max_length=10, null=True),
        ),
    ]
