# Generated by Django 4.1.5 on 2023-12-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0017_alter_verificacassettaps_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacassettaps',
            name='materiale_da_integrare',
            field=models.TextField(blank=True, null=True, verbose_name='Materiale da reintegrare'),
        ),
        migrations.AlterField(
            model_name='verificacassettaps',
            name='materiale_integrato',
            field=models.TextField(blank=True, null=True, verbose_name='Materiale reintegrato'),
        ),
    ]
