# Generated by Django 4.1.5 on 2024-01-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0063_alter_lavoratore_assunzione_and_more'),
        ('sgi', '0018_alter_verificacassettaps_materiale_da_integrare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RilevatoreH2S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(blank=True, choices=[('l', 'Consegnato'), ('f', 'Fornitori'), ('d', 'Disponibile')], max_length=1, null=True)),
                ('marca', models.CharField(blank=True, choices=[('hw', 'Honeywell'), ('dr', 'Drager'), ('ms', 'MSA')], max_length=3, null=True)),
                ('matricola', models.CharField(blank=True, max_length=20, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('data_bump_test', models.DateField(blank=True, null=True)),
                ('lavoratore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personale.lavoratore')),
            ],
        ),
    ]
