# Generated by Django 4.1.5 on 2024-01-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0063_alter_lavoratore_assunzione_and_more'),
        ('sgi', '0019_rilevatoreh2s'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rilevatoreh2s',
            options={'ordering': ['-uso', 'lavoratore'], 'verbose_name': 'Rilevatore H2S', 'verbose_name_plural': 'Rilevatori H2S'},
        ),
        migrations.CreateModel(
            name='DPI_Anticaduta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(blank=True, choices=[('c', 'Consegnato'), ('d', 'Disponibile')], max_length=1, null=True)),
                ('tipologia', models.CharField(blank=True, choices=[('im', 'Imbracatura'), ('c1', 'Cordino Singolo'), ('c2', 'Cordino Doppio')], max_length=2, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modello', models.CharField(blank=True, max_length=20, null=True)),
                ('matricola', models.CharField(blank=True, max_length=20, null=True)),
                ('data_fabbricazione', models.DateField(blank=True, null=True)),
                ('data_messa_in_servizio', models.DateField(blank=True, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('lavoratore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personale.lavoratore')),
            ],
            options={
                'verbose_name': 'DPI Anticaduta',
                'verbose_name_plural': 'DPI Anticaduta',
                'ordering': ['-uso', 'lavoratore'],
            },
        ),
    ]
