# Generated by Django 4.1.5 on 2024-01-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0020_alter_rilevatoreh2s_options_dpi_anticaduta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacassettaps',
            name='note',
        ),
    ]
