# Generated by Django 4.1.5 on 2024-01-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0021_remove_verificacassettaps_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_benda10',
            field=models.DateField(blank=True, null=True, verbose_name='Benda orlata 10cm'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_cerotti',
            field=models.DateField(blank=True, null=True, verbose_name='Cerotti'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_cerotto25',
            field=models.DateField(blank=True, null=True, verbose_name='Cerotto alto 2.5cm'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_cotone',
            field=models.DateField(blank=True, null=True, verbose_name='Cotone idrofilo'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_fisiologica',
            field=models.DateField(blank=True, null=True, verbose_name='Fisiologica 250ml'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_forbici',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_garza10x10',
            field=models.DateField(blank=True, null=True, verbose_name='Garza 10x10'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_garza18x40',
            field=models.DateField(blank=True, null=True, verbose_name='Garza 18x40'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_ghiaccio',
            field=models.DateField(blank=True, null=True, verbose_name='Ghiaccio pronto uso'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_guanti',
            field=models.DateField(blank=True, null=True, verbose_name='Guanti sterili'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_iodio',
            field=models.DateField(blank=True, null=True, verbose_name='Iodiopovidone 125ml'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_istruzioni',
            field=models.BooleanField(blank=True, null=True, verbose_name='Istruzioni/Estratto DLgs 81/08'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_laccio',
            field=models.DateField(blank=True, null=True, verbose_name='Laccio emostatico'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_pinzette',
            field=models.DateField(blank=True, null=True, verbose_name='Pinzette'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc_sacchetto',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sacchetto monouso'),
        ),
    ]
