# Generated by Django 4.1.5 on 2024-01-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0022_verificacassettaps_sc_benda10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_benda10',
            new_name='sc2_benda10',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_cerotti',
            new_name='sc2_cerotti',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_cerotto25',
            new_name='sc2_cerotto25',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_cotone',
            new_name='sc2_cotone',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_fisiologica',
            new_name='sc2_fisiologica',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_forbici',
            new_name='sc2_forbici',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_garza10x10',
            new_name='sc2_garza10x10',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_garza18x40',
            new_name='sc2_garza18x40',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_ghiaccio',
            new_name='sc2_ghiaccio',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_guanti',
            new_name='sc2_guanti',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_iodio',
            new_name='sc2_iodio',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_istruzioni',
            new_name='sc2_istruzioni',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_laccio',
            new_name='sc2_laccio',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_pinzette',
            new_name='sc2_pinzette',
        ),
        migrations.RenameField(
            model_name='verificacassettaps',
            old_name='sc_sacchetto',
            new_name='sc2_sacchetto',
        ),
    ]
