# Generated by Django 4.1.5 on 2024-01-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0023_rename_sc_benda10_verificacassettaps_sc2_benda10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi2',
            name='ck_consegna',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dpi2',
            name='ck_elmetto',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dpi2',
            name='ck_maschera',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dpi2',
            name='ck_rilevatore',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dpi2',
            name='elmetto_df',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data di fabbricazione'),
        ),
    ]
