# Generated by Django 4.1.5 on 2024-02-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0024_dpi2_ck_consegna_dpi2_ck_elmetto_dpi2_ck_maschera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_cerotti',
            field=models.DateField(blank=True, null=True, verbose_name='Cerotti'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_cerotto25',
            field=models.DateField(blank=True, null=True, verbose_name='Cerotto alto 2.5cm'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_cotone',
            field=models.DateField(blank=True, null=True, verbose_name='Cotone idrofilo'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_fisiologica',
            field=models.DateField(blank=True, null=True, verbose_name='Fisiologica 250ml'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_forbici',
            field=models.BooleanField(blank=True, null=True, verbose_name='Forbici'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_garza10x10',
            field=models.DateField(blank=True, null=True, verbose_name='Garza 10x10'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_garza18x40',
            field=models.DateField(blank=True, null=True, verbose_name='Garza 18x40'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_ghiaccio',
            field=models.DateField(blank=True, null=True, verbose_name='Ghiaccio pronto uso'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_guanti',
            field=models.DateField(blank=True, null=True, verbose_name='Guanti sterili'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_iodio',
            field=models.DateField(blank=True, null=True, verbose_name='Iodiopovidone 125ml'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_istruzioni',
            field=models.BooleanField(blank=True, null=True, verbose_name='Istruzioni/Estratto DLgs 81/08'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_laccio',
            field=models.DateField(blank=True, null=True, verbose_name='Laccio emostatico'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_pinzette',
            field=models.DateField(blank=True, null=True, verbose_name='Pinzette'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_rete',
            field=models.DateField(blank=True, null=True, verbose_name='Rete elastica'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_sacchetto',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sacchetto monouso'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_sfigmomanometro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sfigmomanometro'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_teli',
            field=models.DateField(blank=True, null=True, verbose_name='Teli sterili'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_termometro',
            field=models.BooleanField(blank=True, null=True, verbose_name='termometro'),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='sc1_visiera',
            field=models.DateField(blank=True, null=True, verbose_name='Visiera paraschizzi'),
        ),
        migrations.AlterField(
            model_name='verificacassettaps',
            name='sc2_forbici',
            field=models.BooleanField(blank=True, null=True, verbose_name='Forbici'),
        ),
    ]
