# Generated by Django 4.1.5 on 2024-03-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0025_verificacassettaps_sc1_cerotti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_conformita',
            name='area',
            field=models.CharField(blank=True, choices=[('sic', 'Sicurezza'), ('qua', 'Qualità'), ('qhse', 'QHSE')], default='sic', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='non_conformita',
            name='emittente',
            field=models.CharField(blank=True, choices=[('sogein', 'CSE SOGEIN'), ('scc', 'CSE SCC'), ('a_scc', 'Assistente CSE SCC'), ('aspp', 'ASPP'), ('rsgi', 'RSGI'), ('hse eni', 'HSE ENI'), ('a_hse_scc', 'Assistente HSE SCC')], default='aspp', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='non_conformita',
            name='responsabile_trattamento',
            field=models.CharField(blank=True, choices=[('aspp', 'ASPP'), ('rsgi', 'RSGI')], default='aspp', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='non_conformita',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('nc', 'NC'), ('oss', 'OSS')], default='nc', max_length=10, null=True),
        ),
    ]
