# Generated by Django 4.1.5 on 2024-03-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0026_alter_non_conformita_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formazione',
            name='argomento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
