# Generated by Django 4.1.5 on 2024-03-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0027_alter_formazione_argomento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cassettaps',
            options={'ordering': ['numero'], 'verbose_name': 'Cassetta PS', 'verbose_name_plural': 'Cassette PS elenco'},
        ),
        migrations.AlterModelOptions(
            name='verificacassettaps',
            options={'ordering': ['cassetta', '-data_verifica'], 'verbose_name': 'Verifica Cassetta PS', 'verbose_name_plural': 'Cassetta PS verifiche'},
        ),
        migrations.AddField(
            model_name='cassettaps',
            name='ck_scadenza',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
