# Generated by Django 4.1.5 on 2024-03-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0028_alter_cassettaps_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_cerotti',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_cerotto25',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_cotone',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_fisiologica',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_forbici',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_garza10x10',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_garza18x40',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_ghiaccio',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_guanti',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_iodio',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_istruzioni',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_laccio',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_pinzette',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_rete',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_sacchetto',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_sfigmomanometro',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_teli',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_termometro',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc1_visiera',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_benda10',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_cerotti',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_cerotto25',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_cotone',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_fisiologica',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_forbici',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_garza10x10',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_garza18x40',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_ghiaccio',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_guanti',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_iodio',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_istruzioni',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_laccio',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_pinzette',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='ck_sc2_sacchetto',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
