# Generated by Django 4.1.5 on 2024-04-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0029_verificacassettaps_ck_sc1_cerotti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_conformita',
            name='area',
            field=models.CharField(blank=True, choices=[('sic', 'Sicurezza'), ('qua', 'Qualità'), ('qhse', 'QHSE'), ('amb', 'Ambiente')], default='sic', max_length=10, null=True),
        ),
    ]
