# Generated by Django 4.1.5 on 2024-04-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0030_alter_non_conformita_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriSollevamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[], max_length=1, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('anno', models.IntegerField(blank=True, null=True)),
                ('codice', models.CharField(blank=True, max_length=10, null=True)),
                ('diametro', models.CharField(blank=True, choices=[], max_length=5, null=True)),
                ('colore', models.CharField(blank=True, choices=[], max_length=1, null=True)),
                ('lunghezza', models.CharField(blank=True, max_length=10, null=True)),
                ('portata', models.CharField(blank=True, max_length=10, null=True)),
                ('terminali', models.CharField(blank=True, choices=[], max_length=2, null=True)),
                ('reparto', models.CharField(blank=True, max_length=20, null=True)),
                ('usura_leggera', models.BooleanField(blank=True, null=True)),
                ('usura_media', models.BooleanField(blank=True, null=True)),
                ('usura_grave', models.BooleanField(blank=True, null=True)),
                ('usura_sostituzione', models.BooleanField(blank=True, null=True)),
                ('conforme', models.BooleanField(blank=True, null=True)),
                ('data_messa_in_servizio', models.DateTimeField(blank=True, null=True)),
                ('data_dismissione', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
