# Generated by Django 4.1.5 on 2024-04-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0031_accessorisollevamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='data_dismissione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='data_messa_in_servizio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
