# Generated by Django 4.1.5 on 2024-04-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0032_alter_accessorisollevamento_data_dismissione_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessorisollevamento',
            options={'ordering': ['codice'], 'verbose_name': 'Accessorio di sollevamento', 'verbose_name_plural': 'Accessori di sollevamento'},
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='colore',
            field=models.CharField(blank=True, choices=[('a', 'Arancione'), ('b', 'Blu'), ('g', 'Giallo'), ('gr', 'Grigio'), ('m', 'Marrone'), ('v', 'Verde')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='conforme',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='diametro',
            field=models.CharField(blank=True, choices=[('3_4', '3/4"'), ('5_8', '5/8"'), ('7/8', '7/8"')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='terminali',
            field=models.CharField(blank=True, choices=[('an', 'Anello'), ('as', 'Asola')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('car', 'Carrucola + Fune + Moschettone'), ('cat2', 'Tirante in catena a 2 bracci'), ('cat4', 'Tirante in catena a 4 bracci'), ('f', 'Braca fibra sintetica piatta'), ('fc', 'Braca fibra sintetica piatta con cricchetto'), ('grd', 'Grilli di sollevamento dritti'), ('grl', 'Grilli di sollevamento a lira'), ('gs', 'Gancio di sollevamento'), ('pc', 'Pinze di sollevamento casseri PERI'), ('pl', 'Pinze di sollevamento lamiere')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='usura_sostituzione',
            field=models.BooleanField(default=False, verbose_name='Sostituzione'),
        ),
    ]
