# Generated by Django 4.1.5 on 2024-04-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0033_alter_accessorisollevamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='usura_sostituzione',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sostituzione'),
        ),
    ]
