# Generated by Django 4.1.5 on 2024-04-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0034_alter_accessorisollevamento_usura_sostituzione'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorisollevamento',
            name='in_uso',
            field=models.BooleanField(default=True),
        ),
    ]
