# Generated by Django 4.1.5 on 2024-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0035_accessorisollevamento_in_uso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriSollevamento_Revisione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compilazione', models.DateField(blank=True, null=True)),
                ('revisione', models.IntegerField(blank=True, null=True)),
                ('trimestre', models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], max_length=1, null=True)),
                ('anno', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('car', 'Carrucola'), ('cat2', 'Tirante in catena a 2 bracci'), ('cat4', 'Tirante in catena a 4 bracci'), ('f', 'Braca fibra sintetica piatta'), ('fc', 'Braca fibra sintetica piatta con cricchetto'), ('grd', 'Grilli di sollevamento dritti'), ('grl', 'Grilli di sollevamento a lira'), ('gs', 'Gancio di sollevamento'), ('pc', 'Pinze di sollevamento casseri'), ('pl', 'Pinze di sollevamento lamiere')], max_length=4, null=True),
        ),
    ]
