# Generated by Django 4.1.5 on 2024-04-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0036_accessorisollevamento_revisione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorisollevamento',
            name='stato',
            field=models.CharField(blank=True, choices=[('2', 'Nuova'), ('1', 'Ok'), ('-1', 'Dismessa da poco'), ('-2', 'Dismessa')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='terminali',
            field=models.CharField(blank=True, choices=[('an', 'Anello'), ('as', 'Asola'), ('ga', 'Gancio')], max_length=2, null=True),
        ),
    ]
