# Generated by Django 4.1.5 on 2024-04-22 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0066_idoneita_altezza'),
        ('sgi', '0037_accessorisollevamento_stato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinturaSicurezzaConsegna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DPI_Anticaduta_Verifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dpi_anticaduta',
            options={'ordering': ['tipologia', 'matricola'], 'verbose_name': 'DPI Anticaduta', 'verbose_name_plural': 'DPI Anticaduta'},
        ),
        migrations.RenameField(
            model_name='dpi_anticaduta',
            old_name='data_fabbricazione',
            new_name='fabbricazione',
        ),
        migrations.RenameField(
            model_name='dpi_anticaduta',
            old_name='data_messa_in_servizio',
            new_name='messa_in_servizio',
        ),
        migrations.RemoveField(
            model_name='dpi_anticaduta',
            name='data_scadenza',
        ),
        migrations.RemoveField(
            model_name='dpi_anticaduta',
            name='lavoratore',
        ),
        migrations.RemoveField(
            model_name='dpi_anticaduta',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='dpi_anticaduta',
            name='uso',
        ),
        migrations.AddField(
            model_name='dpi_anticaduta',
            name='dismissione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpi_anticaduta',
            name='stato',
            field=models.CharField(blank=True, choices=[('c', 'Consegnato'), ('d', 'Disponibile'), ('x', 'Dismesso')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='stato',
            field=models.CharField(blank=True, choices=[('recente', 'table-success'), ('ok', ''), ('dismessa_recente', 'table-warning'), ('dismessa', 'table-danger')], max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='DPI_Anticaduta_Consegna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('lavoratore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personale.lavoratore')),
            ],
        ),
        migrations.AddField(
            model_name='dpi_anticaduta',
            name='verifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgi.dpi_anticaduta_verifica'),
        ),
    ]
