# Generated by Django 4.1.5 on 2024-04-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0038_cinturasicurezzaconsegna_dpi_anticaduta_verifica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi_anticaduta_consegna',
            name='lavoratore',
        ),
    ]
