# Generated by Django 4.1.5 on 2024-04-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0039_remove_dpi_anticaduta_consegna_lavoratore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPI_Anticaduta2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consegna', models.ManyToManyField(blank=True, null=True, to='sgi.dpi_anticaduta_consegna')),
            ],
        ),
    ]
