# Generated by Django 4.1.5 on 2024-04-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0066_idoneita_altezza'),
        ('sgi', '0040_dpi_anticaduta2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi_anticaduta_consegna',
            name='lavoratore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personale.lavoratore'),
        ),
    ]
