# Generated by Django 4.1.5 on 2024-04-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0041_dpi_anticaduta_consegna_lavoratore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpi_anticaduta',
            options={},
        ),
        migrations.RemoveField(
            model_name='dpi_anticaduta',
            name='stato',
        ),
        migrations.RemoveField(
            model_name='dpi_anticaduta',
            name='tipologia',
        ),
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='stato',
            field=models.CharField(blank=True, choices=[('c', 'Consegnato'), ('d', 'Disponibile'), ('x', 'Dismesso')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('im', 'Imbracatura'), ('c1', 'Cordino Singolo'), ('c2', 'Cordino Doppio')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='dpi_anticaduta2',
            name='consegna',
            field=models.ManyToManyField(blank=True, to='sgi.dpi_anticaduta_consegna'),
        ),
    ]
