# Generated by Django 4.1.5 on 2024-04-22 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0042_alter_dpi_anticaduta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='dismissione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='fabbricazione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='marca',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='matricola',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='messa_in_servizio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='modello',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='verifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgi.dpi_anticaduta_verifica'),
        ),
    ]
