# Generated by Django 4.1.5 on 2024-04-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0043_dpi_anticaduta2_dismissione_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CinturaSicurezzaConsegna',
        ),
        migrations.AlterModelOptions(
            name='dpi_anticaduta2',
            options={'ordering': ['tipologia', 'matricola'], 'verbose_name': 'DPI Anticaduta', 'verbose_name_plural': 'DPI Anticaduta'},
        ),
        migrations.AlterModelOptions(
            name='dpi_anticaduta_consegna',
            options={'ordering': ['data', 'lavoratore'], 'verbose_name': 'DPI Anticaduta Consegna', 'verbose_name_plural': 'DPI Anticaduta Consegne'},
        ),
        migrations.AlterModelOptions(
            name='dpi_anticaduta_verifica',
            options={'ordering': ['data'], 'verbose_name': 'DPI Anticaduta Verifica', 'verbose_name_plural': 'DPI Anticaduta Verifiche'},
        ),
        migrations.DeleteModel(
            name='DPI_Anticaduta',
        ),
    ]
