# Generated by Django 4.1.5 on 2024-04-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0044_delete_cinturasicurezzaconsegna_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessorisollevamento',
            options={'ordering': ['codice'], 'verbose_name': 'Accessorio di Sollevamento', 'verbose_name_plural': 'Accessori di Sollevamento'},
        ),
        migrations.AlterModelOptions(
            name='accessorisollevamento_revisione',
            options={'verbose_name': 'Accessori di Sollevamento Revisione', 'verbose_name_plural': 'Accessori di Sollevamento Revisione'},
        ),
        migrations.AlterField(
            model_name='dpi_anticaduta2',
            name='matricola',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
