# Generated by Django 4.1.5 on 2024-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0045_alter_accessorisollevamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpi_anticaduta2',
            options={'ordering': ['-tipologia', 'matricola'], 'verbose_name': 'DPI Anticaduta', 'verbose_name_plural': 'DPI Anticaduta'},
        ),
        migrations.AlterModelOptions(
            name='dpi_anticaduta_consegna',
            options={'ordering': ['-data', 'lavoratore'], 'verbose_name': 'DPI Anticaduta Consegna', 'verbose_name_plural': 'DPI Anticaduta Consegne'},
        ),
        migrations.AlterModelOptions(
            name='dpi_anticaduta_verifica',
            options={'ordering': ['-data'], 'verbose_name': 'DPI Anticaduta Verifica', 'verbose_name_plural': 'DPI Anticaduta Verifiche'},
        ),
        migrations.AddField(
            model_name='dpi2',
            name='cordino_doppio',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dpi2',
            name='cordino_singolo',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dpi2',
            name='imbracatura',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
