# Generated by Django 4.1.5 on 2024-04-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0046_alter_dpi_anticaduta2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='ck_revisione',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
