# Generated by Django 4.1.5 on 2024-04-26 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0047_dpi_anticaduta2_ck_revisione'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormazioneCantieri_Cantieri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormazioneCantieri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.BinaryField(blank=True, default=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'IFA'), ('1', 'PSC'), ('2', 'POS'), ('3', 'Altro')], max_length=1, null=True)),
                ('tipo_revisione', models.IntegerField(blank=True, null=True)),
                ('tipo_nome', models.CharField(blank=True, max_length=20, null=True)),
                ('ifa_trimestre', models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], max_length=1, null=True)),
                ('ifa_anno', models.IntegerField(blank=True, null=True)),
                ('cantiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgi.formazionecantieri_cantieri')),
            ],
        ),
    ]
