# Generated by Django 4.1.5 on 2024-04-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0048_formazionecantieri_cantieri_formazionecantieri'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormazioneCantieri',
            new_name='FormazioneCantieri_Documento',
        ),
        migrations.AlterModelOptions(
            name='accessorisollevamento_revisione',
            options={'verbose_name': 'Accessori di Sollevamento - Revisione', 'verbose_name_plural': 'Accessori di Sollevamento - Revisioni'},
        ),
        migrations.AlterModelOptions(
            name='cassettaps',
            options={'ordering': ['numero'], 'verbose_name': 'Cassetta PS', 'verbose_name_plural': 'Cassette PS - Elenco'},
        ),
        migrations.AlterModelOptions(
            name='dpi_anticaduta_consegna',
            options={'ordering': ['-data', 'lavoratore'], 'verbose_name': 'DPI Anticaduta - Consegna', 'verbose_name_plural': 'DPI Anticaduta - Consegne'},
        ),
        migrations.AlterModelOptions(
            name='dpi_anticaduta_verifica',
            options={'ordering': ['-data'], 'verbose_name': 'DPI Anticaduta - Verifica', 'verbose_name_plural': 'DPI Anticaduta - Verifiche'},
        ),
        migrations.AlterModelOptions(
            name='formazionecantieri_cantieri',
            options={'ordering': ['nome'], 'verbose_name': 'Formazione Cantiere - Cantiere', 'verbose_name_plural': 'Formazione Cantiere - Cantieri'},
        ),
        migrations.AlterModelOptions(
            name='formazionecantieri_documento',
            options={'ordering': ['cantiere', 'tipo'], 'verbose_name': 'Formazione Cantiere', 'verbose_name_plural': 'Formazione Cantiere'},
        ),
        migrations.AlterModelOptions(
            name='verificacassettaps',
            options={'ordering': ['cassetta', '-data_verifica'], 'verbose_name': 'Cassetta PS - Verifica', 'verbose_name_plural': 'Cassetta PS - Verifiche'},
        ),
    ]
