# Generated by Django 4.1.5 on 2024-04-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0066_idoneita_altezza'),
        ('sgi', '0049_rename_formazionecantieri_formazionecantieri_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormazioneCantieri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.BinaryField(blank=True, default=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'IFA'), ('1', 'PSC'), ('2', 'POS'), ('3', 'Altro')], max_length=1, null=True)),
                ('tipo_revisione', models.IntegerField(blank=True, null=True)),
                ('tipo_nome', models.CharField(blank=True, max_length=20, null=True)),
                ('ifa_trimestre', models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], max_length=1, null=True)),
                ('ifa_anno', models.IntegerField(blank=True, null=True)),
                ('cantiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgi.formazionecantieri_cantieri')),
                ('lavoratori', models.ManyToManyField(to='personale.lavoratore')),
            ],
            options={
                'verbose_name': 'Formazione Cantiere - Documento',
                'verbose_name_plural': 'Formazione Cantiere - Documenti',
                'ordering': ['cantiere', 'tipo', 'tipo_revisione', 'ifa_anno', 'ifa_trimestre'],
            },
        ),
        migrations.DeleteModel(
            name='FormazioneCantieri_Documento',
        ),
    ]
