# Generated by Django 4.1.5 on 2024-04-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0066_idoneita_altezza'),
        ('sgi', '0050_formazionecantieri_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formazionecantieri',
            options={'ordering': ['cantiere', 'tipo', 'tipo_revisione', 'ifa_anno', 'ifa_trimestre'], 'verbose_name': 'Formazione Cantiere', 'verbose_name_plural': 'Formazione Cantiere'},
        ),
        migrations.AlterField(
            model_name='formazionecantieri',
            name='lavoratori',
            field=models.ManyToManyField(blank=True, to='personale.lavoratore'),
        ),
    ]
