# Generated by Django 4.1.5 on 2024-04-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0051_alter_formazionecantieri_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formazionecantieri',
            name='attivo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
