# Generated by Django 4.1.5 on 2024-04-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0052_alter_formazionecantieri_attivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazionecantieri_cantieri',
            name='in_corso',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='formazionecantieri',
            name='attivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formazionecantieri',
            name='tipo_nome',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome altro tipo'),
        ),
        migrations.AlterField(
            model_name='formazionecantieri',
            name='tipo_revisione',
            field=models.IntegerField(blank=True, null=True, verbose_name='Revisione'),
        ),
    ]
