# Generated by Django 4.1.5 on 2024-04-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0053_formazionecantieri_cantieri_in_corso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formazionecantieri',
            options={'ordering': ['cantiere', 'tipo', 'tipo_revisione', 'ifa_trimestre'], 'verbose_name': 'Formazione Cantiere', 'verbose_name_plural': 'Formazione Cantiere'},
        ),
        migrations.RemoveField(
            model_name='formazionecantieri',
            name='ifa_anno',
        ),
    ]
