# Generated by Django 4.1.5 on 2024-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0054_alter_formazionecantieri_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazionecantieri_cantieri',
            name='tipo',
            field=models.CharField(blank=True, choices=[('0', 'DUVRI'), ('1', 'TITOLO IV (sotto Coordinamento)'), ('2', 'Cantieri Esterni')], max_length=1, null=True),
        ),
    ]
