# Generated by Django 4.1.5 on 2024-06-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0055_formazionecantieri_cantieri_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpi_anticaduta2',
            options={'ordering': ['-tipologia', 'stato', 'matricola'], 'verbose_name': 'DPI Anticaduta', 'verbose_name_plural': 'DPI Anticaduta'},
        ),
        migrations.AlterModelOptions(
            name='formazionecantieri_cantieri',
            options={'ordering': ['tipo', 'nome'], 'verbose_name': 'Formazione Cantiere - Cantiere', 'verbose_name_plural': 'Formazione Cantiere - Cantieri'},
        ),
        migrations.AddField(
            model_name='rilevatoreh2s',
            name='data_calibrazione',
            field=models.DateField(blank=True, null=True),
        ),
    ]
