# Generated by Django 4.1.5 on 2024-06-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0056_alter_dpi_anticaduta2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rilevatoreh2s',
            name='data_calibrazione_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], max_length=15, null=True),
        ),
    ]
