# Generated by Django 4.1.5 on 2024-06-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0057_rilevatoreh2s_data_calibrazione_ck'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi2',
            name='ck_rilevatore_calibrazione',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rilevatoreh2s',
            name='data_calibrazione_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'in scadenza'), ('table-danger', 'scaduto')], max_length=15, null=True),
        ),
    ]
