# Generated by Django 4.1.5 on 2024-06-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0058_dpi2_ck_rilevatore_calibrazione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formazione_Organico_Medio_Annuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(blank=True, null=True)),
                ('valore', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Formazione - Organico Medio Annuo',
                'verbose_name_plural': 'Formazione - Organico Medio Annuo',
                'ordering': ['-anno'],
            },
        ),
    ]
