# Generated by Django 4.1.5 on 2024-07-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0059_formazione_organico_medio_annuo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formazione_organico_medio_annuo',
            options={'ordering': ['-anno'], 'verbose_name': 'Formazione - Organico Medio Annuo', 'verbose_name_plural': 'Formazioni - Organico Medio Annuo'},
        ),
        migrations.AddField(
            model_name='verificacassettaps',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
