# Generated by Django 4.1.5 on 2024-07-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0060_alter_formazione_organico_medio_annuo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='matricola_interna',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
