# Generated by Django 4.1.5 on 2024-07-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0061_dpi_anticaduta2_matricola_interna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpi_anticaduta2',
            options={'ordering': ['-tipologia', 'stato', 'matricola_interna'], 'verbose_name': 'DPI Anticaduta', 'verbose_name_plural': 'DPI Anticaduta'},
        ),
        migrations.AlterModelOptions(
            name='rilevatoreh2s',
            options={'ordering': ['uso', 'lavoratore'], 'verbose_name': 'Rilevatore H2S', 'verbose_name_plural': 'Rilevatori H2S'},
        ),
        migrations.AddField(
            model_name='non_conformita',
            name='delimitazioni',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='stato',
            field=models.CharField(blank=True, choices=[('recente', 'table-success'), ('ok', ''), ('dismessa_recente', 'table-danger'), ('dismessa', 'table-danger')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='dpi_anticaduta2',
            name='stato',
            field=models.CharField(blank=True, choices=[('c', 'Consegnato'), ('d', 'Disponibile'), ('v', 'Verifica'), ('x', 'Dismesso')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='rilevatoreh2s',
            name='uso',
            field=models.CharField(blank=True, choices=[('l', 'Consegnato'), ('f', 'Fornitori'), ('d', 'Disponibile'), ('x', 'Dismesso')], max_length=1, null=True),
        ),
    ]
