# Generated by Django 4.1.5 on 2024-07-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0062_alter_dpi_anticaduta2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='non_conformita',
            name='attrezzature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='non_conformita',
            name='dpi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='non_conformita',
            name='gravita',
            field=models.CharField(blank=True, choices=[('1', 'Grigia'), ('2', 'Gialla'), ('3', 'Rossa')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='non_conformita',
            name='guida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='non_conformita',
            name='lavori_quota',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='non_conformita',
            name='ordine_pulizia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='non_conformita',
            name='pdl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='non_conformita',
            name='ponteggio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='non_conformita',
            name='ponteggio_stato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='non_conformita',
            name='ponteggio_uso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='non_conformita',
            name='sollevamenti',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='non_conformita',
            name='spazi_confinati',
            field=models.BooleanField(default=False),
        ),
    ]
