# Generated by Django 4.1.5 on 2024-08-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0068_idoneita_flessioni_rachide'),
        ('sgi', '0063_non_conformita_attrezzature_non_conformita_dpi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPI_Anticaduta_Operazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('operazione', models.CharField(blank=True, choices=[('ms', 'Messa in servizio'), ('c', 'Consegnato'), ('d', 'Riconsegna - Disponibile'), ('rv', 'Riconsegna per Verifica'), ('v', 'Verifica'), ('x', 'Dismesso')], max_length=2, null=True)),
                ('lavoratore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personale.lavoratore')),
            ],
            options={
                'verbose_name': 'DPI Anticaduta - Operazione',
                'verbose_name_plural': 'DPI Anticaduta - Operazioni',
                'ordering': ['-data', 'lavoratore'],
            },
        ),
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='operazione',
            field=models.ManyToManyField(blank=True, to='sgi.dpi_anticaduta_operazione'),
        ),
    ]
