# Generated by Django 4.1.5 on 2024-08-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0064_dpi_anticaduta_operazione_dpi_anticaduta2_operazione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpi_anticaduta_operazione',
            options={'ordering': ['data', 'lavoratore'], 'verbose_name': 'DPI Anticaduta - Operazione', 'verbose_name_plural': 'DPI Anticaduta - Operazioni'},
        ),
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='data_verifica',
            field=models.DateField(blank=True, null=True),
        ),
    ]
