# Generated by Django 4.1.5 on 2024-08-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0068_idoneita_flessioni_rachide'),
        ('sgi', '0065_alter_dpi_anticaduta_operazione_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='lavoratore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personale.lavoratore'),
        ),
        migrations.AlterField(
            model_name='dpi_anticaduta2',
            name='data_verifica',
            field=models.DateField(blank=True, null=True, verbose_name='Data ultima verifica'),
        ),
    ]
