# Generated by Django 4.1.5 on 2024-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0066_dpi_anticaduta2_lavoratore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='consegna2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dpi_anticaduta2',
            name='matricola_interna',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dpi_anticaduta_operazione',
            name='operazione',
            field=models.CharField(blank=True, choices=[('ms', 'Messa in servizio'), ('c', 'Consegnato'), ('d', 'Riconsegna/Disponibile'), ('rv', 'Riconsegna per Verifica'), ('v', 'Verifica'), ('x', 'Dismesso')], max_length=2, null=True),
        ),
    ]
