# Generated by Django 4.1.5 on 2024-09-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0067_dpi_anticaduta2_consegna2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi_anticaduta2',
            name='consegna',
        ),
        migrations.RemoveField(
            model_name='dpi_anticaduta2',
            name='verifica',
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='anno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anno Produzione'),
        ),
        migrations.AlterField(
            model_name='dpi_anticaduta2',
            name='consegna2',
            field=models.DateField(blank=True, null=True, verbose_name='Ultima operazione'),
        ),
        migrations.DeleteModel(
            name='DPI_Anticaduta_Consegna',
        ),
        migrations.DeleteModel(
            name='DPI_Anticaduta_Verifica',
        ),
    ]
