# Generated by Django 4.1.5 on 2024-09-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0068_idoneita_flessioni_rachide'),
        ('sgi', '0068_remove_dpi_anticaduta2_consegna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPI_Anticaduta_Verifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DPI Anticaduta - Verifica',
                'verbose_name_plural': 'DPI Anticaduta - Verifiche',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='DPI_Anticaduta_Consegna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('lavoratore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personale.lavoratore')),
            ],
            options={
                'verbose_name': 'DPI Anticaduta - Consegna',
                'verbose_name_plural': 'DPI Anticaduta - Consegne',
                'ordering': ['-data', 'lavoratore'],
            },
        ),
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='consegna',
            field=models.ManyToManyField(blank=True, to='sgi.dpi_anticaduta_consegna'),
        ),
        migrations.AddField(
            model_name='dpi_anticaduta2',
            name='verifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgi.dpi_anticaduta_verifica'),
        ),
    ]
