# Generated by Django 4.1.5 on 2024-09-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0069_dpi_anticaduta_verifica_dpi_anticaduta_consegna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi_anticaduta2',
            name='verifica',
        ),
    ]
