# Generated by Django 4.1.5 on 2024-09-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0070_remove_dpi_anticaduta2_verifica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi_anticaduta_consegna',
            name='lavoratore',
        ),
        migrations.DeleteModel(
            name='DPI_Anticaduta_Verifica',
        ),
        migrations.RemoveField(
            model_name='dpi_anticaduta2',
            name='consegna',
        ),
        migrations.DeleteModel(
            name='DPI_Anticaduta_Consegna',
        ),
    ]
