# Generated by Django 4.1.5 on 2024-09-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0071_remove_dpi_anticaduta_consegna_lavoratore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi_anticaduta2',
            name='operazione',
            field=models.ManyToManyField(blank=True, null=True, to='sgi.dpi_anticaduta_operazione'),
        ),
    ]
