# Generated by Django 4.1.5 on 2024-09-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0072_alter_dpi_anticaduta2_operazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('obb', 'Obblighi legge'), ('tiv', 'Cantieri Titolo IV'), ('ifa', 'IFA'), ('scc', 'Patto Sicurezza'), ('sgi', 'SGI')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dpi_anticaduta2',
            name='operazione',
            field=models.ManyToManyField(blank=True, to='sgi.dpi_anticaduta_operazione'),
        ),
    ]
