# Generated by Django 4.1.5 on 2024-09-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0073_formazione_tipologia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rilevatoreh2s',
            options={'ordering': ['uso', 'lavoratore', 'matricola'], 'verbose_name': 'Rilevatore H2S', 'verbose_name_plural': 'Rilevatori H2S'},
        ),
        migrations.AlterField(
            model_name='formazione',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('ifa', 'IFA'), ('obb', 'Obblighi legge'), ('tiv', 'Cantieri Titolo IV'), ('scc', 'Patto Sicurezza'), ('sgi', 'SGI')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rilevatoreh2s',
            name='uso',
            field=models.CharField(blank=True, choices=[('l', 'Consegnato'), ('f', 'Fornitori'), ('d', 'Disponibile'), ('m', 'Multigas'), ('x', 'Dismesso')], max_length=1, null=True),
        ),
    ]
