# Generated by Django 4.1.5 on 2024-10-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0074_alter_rilevatoreh2s_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi_anticaduta2',
            name='stato',
            field=models.CharField(blank=True, choices=[('c', 'Consegnato'), ('d', 'Disponibile'), ('v', 'Riconsegnato per verifica'), ('vi', 'In Verifica'), ('vd', 'Verificata da riconsegnare'), ('x', 'Dismesso')], max_length=2, null=True),
        ),
    ]
