# Generated by Django 4.1.5 on 2024-10-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0075_alter_dpi_anticaduta2_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi_anticaduta_operazione',
            name='operazione',
            field=models.CharField(blank=True, choices=[('ms', 'Messa in servizio'), ('c', 'Consegnato'), ('d', 'Riconsegna/Disponibile'), ('rv', 'Riconsegna per Verifica'), ('vi', 'In Verifica'), ('v', 'Verifica'), ('x', 'Dismesso')], max_length=2, null=True),
        ),
    ]
