# Generated by Django 4.1.5 on 2025-01-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0077_alter_accessorisollevamento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='diametro',
            field=models.CharField(blank=True, choices=[('3_4', '3/4"'), ('5_8', '5/8"'), ('7/8', '7/8"'), ('1__1_4', '1+1/4"')], max_length=6, null=True),
        ),
    ]
