# Generated by Django 4.1.5 on 2025-02-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0078_alter_accessorisollevamento_diametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearMiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('tipologia', models.CharField(blank=True, choices=[('nm', 'Near Miss'), ('med', 'Medicazione'), ('inf', 'Infortunio'), ('inc', 'Incidente')], max_length=3, null=True)),
                ('infortunato', models.CharField(blank=True, max_length=50, null=True)),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name="Descrizione dell'evento")),
                ('cause', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MIP',
                'verbose_name_plural': 'MIP',
                'ordering': ['-data'],
            },
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='diametro',
            field=models.CharField(blank=True, choices=[('12', '12mm'), ('20', '20mm'), ('23', '23mm'), ('26', '26mm'), ('32', '32mm'), ('1_2', '1/2"'), ('3_4', '3/4"'), ('5_8', '5/8"'), ('7/8', '7/8"'), ('1__1_4', '1+1/4"')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('car', 'Carrucola'), ('cat2', 'Tirante in catena a 2 bracci'), ('cat4', 'Tirante in catena a 4 bracci'), ('f', 'Braca fibra sintetica piatta'), ('fc', 'Braca fibra sintetica piatta con cricchetto'), ('grd', 'Grilli di sollevamento dritti'), ('grl', 'Grilli di sollevamento a lira'), ('gs', 'Gancio di sollevamento'), ('pc', 'Pinze di sollevamento casseri'), ('pr', 'Pinze di sollevamento cordoli'), ('pl', 'Pinze di sollevamento lamiere'), ('pp', 'Pinze di sollevamento pozzetti')], max_length=4, null=True),
        ),
    ]
