# Generated by Django 4.1.5 on 2025-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0079_nearmiss_alter_accessorisollevamento_diametro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpi_anticaduta_operazione',
            options={'ordering': ['data', 'pk', 'lavoratore'], 'verbose_name': 'DPI Anticaduta - Operazione', 'verbose_name_plural': 'DPI Anticaduta - Operazioni'},
        ),
        migrations.RemoveField(
            model_name='accessorisollevamento',
            name='usura_sostituzione',
        ),
        migrations.AddField(
            model_name='accessorisollevamento',
            name='usura',
            field=models.CharField(blank=True, choices=[('0', 'ok'), ('1', 'leggero'), ('2', 'medio'), ('3', 'grave')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='colore',
            field=models.CharField(blank=True, choices=[('a', 'Arancione'), ('b', 'Blu'), ('g', 'Giallo'), ('gr', 'Grigio'), ('m', 'Marrone'), ('r', 'Rosso'), ('v', 'Verde')], max_length=2, null=True),
        ),
    ]
