# Generated by Django 4.1.5 on 2025-05-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0080_alter_dpi_anticaduta_operazione_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formazione',
            name='mese',
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('car', 'Carrucola'), ('cat2', 'Tirante in catena a 2 bracci'), ('cat4', 'Tirante in catena a 4 bracci'), ('f', 'Braca fibra sintetica piatta'), ('fa', 'Braca fibra sintetica piatta ad anello'), ('fc', 'Braca fibra sintetica piatta con cricchetto'), ('grd', 'Grilli di sollevamento dritti'), ('grl', 'Grilli di sollevamento a lira'), ('gs', 'Gancio di sollevamento'), ('pc', 'Pinze di sollevamento casseri'), ('pr', 'Pinze di sollevamento cordoli'), ('pl', 'Pinze di sollevamento lamiere'), ('pp', 'Pinze di sollevamento pozzetti')], max_length=4, null=True),
        ),
    ]
