# Generated by Django 4.1.5 on 2025-05-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0081_remove_formazione_mese_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassettaps',
            name='ck_ultima_verifica',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
