# Generated by Django 4.1.5 on 2025-07-25 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0074_alter_lavoratore_assunzione_and_more'),
        ('sgi', '0082_cassettaps_ck_ultima_verifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorisollevamento_revisione',
            name='verificatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personale.lavoratore'),
        ),
        migrations.AlterField(
            model_name='accessorisollevamento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('car', 'Carrucola'), ('cat2', 'Tirante in catena a 2 bracci'), ('cat4', 'Tirante in catena a 4 bracci'), ('f', 'Braca fibra sintetica'), ('fa', 'Braca fibra sintetica ad anello'), ('fc', 'Braca fibra sintetica con cricchetto'), ('grd', 'Grilli di sollevamento dritti'), ('grl', 'Grilli di sollevamento a lira'), ('gs', 'Gancio di sollevamento'), ('pc', 'Pinze di sollevamento casseri'), ('pr', 'Pinze di sollevamento cordoli'), ('pl', 'Pinze di sollevamento lamiere'), ('pp', 'Pinze di sollevamento pozzetti')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='dpi_anticaduta2',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('im', 'Imbracatura'), ('c1', 'Cordino Singolo'), ('c2', 'Cordino Doppio'), ('rt', 'Retrattile')], max_length=2, null=True),
        ),
    ]
