# Generated by Django 4.0.2 on 2022-04-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='assicurazione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='inail',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='marca',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='matricola',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='modello',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='rct',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='revisione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='targa',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('aut', 'auto'), ('car', 'carrello'), ('dum', 'dumper'), ('esc', 'escavatore'), ('fur', 'furgone'), ('pal', 'pala'), ('ple', 'ple'), ('rul', 'rullo'), ('sol', 'sollevatore'), ('ter', 'terna')], default=None, max_length=3, null=True),
        ),
    ]
