# Generated by Django 4.0.2 on 2022-04-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0002_mezzo_assicurazione_mezzo_inail_mezzo_marca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mezzo',
            options={'ordering': ['tipologia', 'marca', 'modello', 'targa', 'matricola'], 'verbose_name': 'Mezzo', 'verbose_name_plural': 'Mezzi'},
        ),
    ]
