# Generated by Django 4.0.2 on 2022-04-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0003_alter_mezzo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('aut', 'Auto'), ('car', 'Carrello'), ('dum', 'Dumper'), ('esc', 'Escavatore'), ('fur', 'Furgone'), ('pal', 'Pala'), ('ple', 'PLE'), ('rul', 'Rullo'), ('sol', 'Sollevatore'), ('ter', 'Terna')], default=None, max_length=3, null=True),
        ),
    ]
