# Generated by Django 4.0.2 on 2022-04-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0004_alter_mezzo_tipologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='ce',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mezzo',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('aut', 'Auto'), ('fur', 'Furgone'), ('esc', 'Escavatore'), ('pal', 'Pala'), ('ter', 'Terna'), ('car', 'Carrello'), ('sol', 'Sollevatore'), ('ple', 'PLE'), ('bet', 'Betoniera'), ('dum', 'Dumper'), ('rul', 'Rullo')], default=None, max_length=3, null=True),
        ),
    ]
