# Generated by Django 4.0.2 on 2022-04-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0005_mezzo_ce_alter_mezzo_tipologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='libretto',
            field=models.BooleanField(default=True),
        ),
    ]
