# Generated by Django 4.0.2 on 2022-04-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0006_mezzo_libretto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='libretto',
            field=models.BooleanField(default=None),
        ),
    ]
