# Generated by Django 4.0.2 on 2022-04-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0008_alter_mezzo_tipologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='ce',
            field=models.BooleanField(default=False),
        ),
    ]
