# Generated by Django 4.0.2 on 2022-04-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0009_alter_mezzo_ce'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scadenza', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mezzo',
            name='rct',
        ),
        migrations.AddField(
            model_name='mezzo',
            name='rct_aziendale',
            field=models.BooleanField(default=False),
        ),
    ]
