# Generated by Django 4.0.2 on 2022-04-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0010_rct_remove_mezzo_rct_mezzo_rct_aziendale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rct',
            options={'verbose_name': 'RCT Aziendale', 'verbose_name_plural': 'RCT Aziendale'},
        ),
        migrations.AlterField(
            model_name='mezzo',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('aut', 'Auto'), ('auc', 'Autocarro'), ('bet', 'Betoniera'), ('car', 'Carrello'), ('dum', 'Dumper'), ('esc', 'Escavatore'), ('fur', 'Furgone'), ('pal', 'Pala'), ('ple', 'PLE'), ('rim', 'Rimorchio'), ('rul', 'Rullo'), ('sol', 'Sollevatore'), ('ter', 'Terna')], default=None, max_length=3, null=True),
        ),
    ]
