# Generated by Django 4.0.2 on 2022-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0011_alter_rct_options_alter_mezzo_tipologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='immatricolazione',
            field=models.DateField(blank=True, null=True),
        ),
    ]
