# Generated by Django 4.0.2 on 2022-04-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0012_mezzo_immatricolazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='ce_accessori',
            field=models.BooleanField(default=False),
        ),
    ]
