# Generated by Django 4.0.2 on 2022-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0013_mezzo_ce_accessori'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='matricola_inail',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
