# Generated by Django 4.0.2 on 2022-05-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0014_mezzo_matricola_inail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='libretto_inail',
            field=models.BooleanField(default=False),
        ),
    ]
