# Generated by Django 4.0.2 on 2022-05-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0015_mezzo_libretto_inail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='manuale',
            field=models.BooleanField(default=False),
        ),
    ]
