# Generated by Django 4.0.2 on 2022-05-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0016_mezzo_manuale'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='faldone',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
