# Generated by Django 4.0.2 on 2022-05-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0017_mezzo_faldone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='matricola_inail',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
