# Generated by Django 4.0.2 on 2022-06-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0019_mezzo_assicurazione_ck_mezzo_inail_ck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='inail',
            field=models.DateField(blank=True, null=True, verbose_name='Verifica Periodica'),
        ),
        migrations.AlterField(
            model_name='mezzo',
            name='inail_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True, verbose_name='Verifica Periodica ck'),
        ),
    ]
