# Generated by Django 4.1.5 on 2025-08-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0020_alter_mezzo_inail_alter_mezzo_inail_ck'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='stato',
            field=models.CharField(blank=True, choices=[('verde', 'ok'), ('giallo', 'scade'), ('rosso', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
