# Generated by Django 4.1.5 on 2025-08-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0021_mezzo_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='rct_aziendale_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
