# Generated by Django 4.1.5 on 2025-08-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0022_mezzo_rct_aziendale_ck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='rct_aziendale_ck',
            field=models.CharField(blank=True, choices=[('verde', 'ok'), ('giallo', 'scade'), ('rosso', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
