# Generated by Django 4.1.5 on 2025-08-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0023_alter_mezzo_rct_aziendale_ck'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='consegnato_ap',
            field=models.BooleanField(blank=True, null=True, verbose_name='Badge AP consegnato'),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='scadenza_ap',
            field=models.IntegerField(blank=True, null=True, verbose_name='Scadenza badge AP'),
        ),
    ]
