# Generated by Django 4.1.5 on 2025-08-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzi', '0024_mezzo_consegnato_ap_mezzo_scadenza_ap'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='scc_numero_verifica',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Numero verifica SCC'),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='scc_verificato',
            field=models.BooleanField(blank=True, null=True, verbose_name='Mezzo verificato SCC'),
        ),
    ]
