# Generated by Django 4.0.2 on 2022-02-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavoratore',
            name='assunzione',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='attivita_svolta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='busta_paga',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='cellulare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='cf',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='data_fine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='data_inizio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='data_nascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='livello',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='luogo_nascita',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='mansione_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='mansione_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='mansione_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='matricola',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='provincia_nascita',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='qualifica',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='reparto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='sesso',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='tipo_contratto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='cognome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
