# Generated by Django 4.0.2 on 2022-02-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0002_lavoratore_assunzione_lavoratore_attivita_svolta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lavoratore',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'Lavoratore', 'verbose_name_plural': 'Lavoratori'},
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='cap',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='citta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='mansione',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='provincia',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='cf',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CF'),
        ),
    ]
