# Generated by Django 4.0.2 on 2022-02-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0003_alter_lavoratore_options_lavoratore_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavoratore',
            name='in_forza',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
