# Generated by Django 4.0.2 on 2022-02-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0004_lavoratore_in_forza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoratore',
            name='in_forza',
            field=models.BooleanField(default=True),
        ),
    ]
