# Generated by Django 4.0.2 on 2022-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0005_alter_lavoratore_in_forza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoratore',
            name='cap',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='provincia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='provincia_nascita',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
