# Generated by Django 4.0.2 on 2022-02-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0007_alter_lavoratore_reparto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoratore',
            name='cap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
