# Generated by Django 4.0.2 on 2022-02-23 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0008_alter_lavoratore_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preposto', models.DateField(blank=True, default=None, null=True)),
                ('preposto_ck', models.BooleanField(blank=True, default=None, null=True)),
                ('primo_soccorso', models.DateField(blank=True, default=None, null=True)),
                ('primo_soccorso_ck', models.BooleanField(blank=True, default=None, null=True)),
                ('antincendio', models.DateField(blank=True, default=None, null=True)),
                ('antincendio_ck', models.BooleanField(blank=True, default=None, null=True)),
                ('art37', models.DateField(blank=True, default=None, null=True)),
                ('art37_ck', models.BooleanField(blank=True, default=None, null=True)),
                ('spazi_confinati', models.DateField(blank=True, default=None, null=True)),
                ('spazi_confinati_ck', models.BooleanField(blank=True, default=None, null=True)),
                ('ponteggiatore', models.DateField(blank=True, default=None, null=True)),
                ('ponteggiatore_ck', models.BooleanField(blank=True, default=None, null=True)),
                ('autogru', models.DateField(blank=True, default=None, null=True)),
                ('autogru_ck', models.BooleanField(blank=True, default=None, null=True)),
                ('carrello', models.DateField(blank=True, default=None, null=True)),
                ('carrello_ck', models.BooleanField(blank=True, default=None, null=True)),
                ('ple', models.DateField(blank=True, default=None, null=True)),
                ('ple_ck', models.BooleanField(blank=True, default=None, null=True)),
                ('lavoratore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.lavoratore')),
            ],
        ),
    ]
