# Generated by Django 4.0.2 on 2022-02-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0009_formazione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formazione',
            options={'ordering': ['lavoratore'], 'verbose_name': 'Formazione', 'verbose_name_plural': 'Formazione'},
        ),
        migrations.AddField(
            model_name='formazione',
            name='gru_autocarro',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='gru_autocarro_ck',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
