# Generated by Django 4.0.2 on 2022-02-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0010_alter_formazione_options_formazione_gru_autocarro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='imbracatore',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='imbracatore_ck',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
