# Generated by Django 4.0.2 on 2022-02-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0011_formazione_imbracatore_formazione_imbracatore_ck'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='rls',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='rls_ck',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
