# Generated by Django 4.0.2 on 2022-02-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0012_formazione_rls_formazione_rls_ck'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='ept',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='ept_ck',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
