# Generated by Django 4.0.2 on 2022-03-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0013_formazione_ept_formazione_ept_ck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formazione',
            name='primo_soccorso_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
