# Generated by Django 4.0.2 on 2022-03-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0015_alter_formazione_antincendio_ck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantiere', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
