# Generated by Django 4.0.2 on 2022-03-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0016_cantiere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cantiere',
            options={'ordering': ['cantiere'], 'verbose_name': 'Cantiere', 'verbose_name_plural': 'Cantieri'},
        ),
    ]
