# Generated by Django 4.0.2 on 2022-03-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0017_alter_cantiere_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavoratore',
            name='cantiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personale.cantiere'),
        ),
    ]
