# Generated by Django 4.0.2 on 2022-03-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0018_lavoratore_cantiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idoneità',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idoneita', models.DateField(blank=True, default=None, null=True)),
                ('idoneita_ck', models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True)),
                ('lavoratore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.lavoratore')),
            ],
            options={
                'verbose_name': 'Idoneità',
                'verbose_name_plural': 'Idoneità',
                'ordering': ['lavoratore'],
            },
        ),
    ]
