# Generated by Django 4.0.2 on 2022-03-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0019_idoneità'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Idoneità',
            new_name='Idoneita',
        ),
    ]
