# Generated by Django 4.0.2 on 2022-03-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0021_formazione_sollevatore_formazione_sollevatore_ck'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='aspp',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='aspp_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
