# Generated by Django 4.0.2 on 2022-03-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0022_formazione_aspp_formazione_aspp_ck'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='otoprotettori',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
