# Generated by Django 4.0.2 on 2022-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0023_idoneita_otoprotettori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idoneita',
            name='otoprotettori',
            field=models.BooleanField(default=False),
        ),
    ]
