# Generated by Django 4.0.2 on 2022-03-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0024_alter_idoneita_otoprotettori'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='guanti',
            field=models.BooleanField(default=False),
        ),
    ]
