# Generated by Django 4.0.2 on 2022-03-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0025_idoneita_guanti'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='carichi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idoneita',
            name='posture',
            field=models.BooleanField(default=False),
        ),
    ]
