# Generated by Django 4.0.2 on 2022-03-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0026_idoneita_carichi_idoneita_posture'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='sollecitazioni_arto_superiore_sinistro',
            field=models.BooleanField(default=False),
        ),
    ]
