# Generated by Django 4.0.2 on 2022-03-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0027_idoneita_sollecitazioni_arto_superiore_sinistro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idoneita',
            old_name='carichi',
            new_name='carichi_15',
        ),
    ]
