# Generated by Django 4.0.2 on 2022-03-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0028_rename_carichi_idoneita_carichi_15'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='carichi_10',
            field=models.BooleanField(default=False),
        ),
    ]
