# Generated by Django 4.0.2 on 2022-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0029_idoneita_carichi_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='spazi_confinati',
            field=models.BooleanField(default=False),
        ),
    ]
