# Generated by Django 4.0.2 on 2022-03-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0030_idoneita_spazi_confinati'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='mansioni_gravose',
            field=models.BooleanField(default=False),
        ),
    ]
