# Generated by Django 4.0.2 on 2022-03-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0031_idoneita_mansioni_gravose'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='temperature',
            field=models.BooleanField(default=False),
        ),
    ]
