# Generated by Django 4.0.2 on 2022-03-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0032_idoneita_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='nomina_antincendio',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='nomina_preposto',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='nomina_primo_soccorso',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
