# Generated by Django 4.0.2 on 2022-03-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0033_formazione_nomina_antincendio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='nomina_aspp',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
