# Generated by Django 4.0.2 on 2022-03-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0034_formazione_nomina_aspp'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='dirigente',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='dirigente_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
