# Generated by Django 4.0.2 on 2022-03-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0035_formazione_dirigente_formazione_dirigente_ck'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='stato',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
