# Generated by Django 4.0.2 on 2022-03-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0036_formazione_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formazione',
            name='stato',
            field=models.CharField(blank=True, choices=[('verde', 'ok_np'), ('giallo', 'scade'), ('rosso', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
