# Generated by Django 4.0.2 on 2022-04-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0038_alter_formazione_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='antincendio_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='art37_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='aspp_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='autogru_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='carrello_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='dirigente_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='ept_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='gru_autocarro_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='imbracatore_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='ple_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='ponteggiatore_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='preposto_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='primo_soccorso_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='rls_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='sollevatore_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='spazi_confinati_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
