# Generated by Django 4.0.2 on 2022-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0039_formazione_antincendio_dc_formazione_art37_dc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoratore',
            name='attivita_svolta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='mansione',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='mansione_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='mansione_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='mansione_3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
