# Generated by Django 4.0.2 on 2022-06-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0040_alter_lavoratore_attivita_svolta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='scale',
            field=models.BooleanField(default=False),
        ),
    ]
