# Generated by Django 4.0.2 on 2022-06-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0041_idoneita_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='calzature',
            field=models.BooleanField(default=False),
        ),
    ]
