# Generated by Django 4.0.2 on 2022-09-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0042_idoneita_calzature'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='nomina_preposto_imbracatore',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='preposto_imbracatore_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
    ]
