# Generated by Django 4.0.2 on 2022-09-08 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0043_formazione_nomina_preposto_imbracatore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formazione',
            name='preposto_imbracatore_ck',
        ),
    ]
