# Generated by Django 4.0.2 on 2022-09-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0044_remove_formazione_preposto_imbracatore_ck'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='nomina_preposto_subappalti',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
