# Generated by Django 4.0.2 on 2022-10-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0045_formazione_nomina_preposto_subappalti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoratore',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
