# Generated by Django 4.1.5 on 2023-01-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0046_alter_lavoratore_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='dumper',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='dumper_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='dumper_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
