# Generated by Django 4.1.5 on 2023-04-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0047_formazione_dumper_formazione_dumper_ck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoratore',
            name='busta_paga',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
