# Generated by Django 4.1.5 on 2023-04-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0048_alter_lavoratore_busta_paga'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='lenti',
            field=models.BooleanField(default=False),
        ),
    ]
