# Generated by Django 4.1.5 on 2023-05-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0049_idoneita_lenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='rumore50',
            field=models.BooleanField(default=False),
        ),
    ]
