# Generated by Django 4.1.5 on 2023-06-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0050_idoneita_rumore50'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='rullo',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='rullo_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='rullo_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
