# Generated by Django 4.1.5 on 2023-08-21 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0051_formazione_rullo_formazione_rullo_ck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consegna', models.DateField(blank=True, default=None, null=True)),
                ('lavoratore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.lavoratore')),
            ],
            options={
                'verbose_name': 'Consegna DPI',
                'verbose_name_plural': 'Consegne DPI',
                'ordering': ['lavoratore'],
            },
        ),
    ]
