# Generated by Django 4.1.5 on 2023-09-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0052_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi',
            name='elmetto',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dpi',
            name='rilevatore',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
