# Generated by Django 4.1.5 on 2023-09-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0053_dpi_elmetto_dpi_rilevatore'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi',
            name='maschera',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
