# Generated by Django 4.1.5 on 2023-09-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0054_dpi_maschera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpi',
            old_name='elmetto',
            new_name='elmetto_df',
        ),
    ]
