# Generated by Django 4.1.5 on 2023-09-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0055_rename_elmetto_dpi_elmetto_df'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi',
            name='elmetto',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
