# Generated by Django 4.1.5 on 2023-10-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0056_dpi_elmetto'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='semestrale',
            field=models.BooleanField(default=False),
        ),
    ]
