# Generated by Django 4.1.5 on 2023-11-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0057_idoneita_semestrale'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='sollecitazioni_rachide',
            field=models.BooleanField(default=False),
        ),
    ]
