# Generated by Django 4.1.5 on 2023-11-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0058_idoneita_sollecitazioni_rachide'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='dpi_respiratori',
            field=models.BooleanField(default=False),
        ),
    ]
