# Generated by Django 4.1.5 on 2023-11-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0059_idoneita_dpi_respiratori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idoneita',
            name='dpi_respiratori',
            field=models.BooleanField(default=False, verbose_name='Uso diligente di idonei DPI respiratori'),
        ),
    ]
