# Generated by Django 4.1.5 on 2023-12-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0060_alter_idoneita_dpi_respiratori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lavoratore',
            name='reparto',
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
