# Generated by Django 4.1.5 on 2024-01-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0061_remove_lavoratore_reparto_lavoratore_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lavoratore',
            name='attivita_svolta',
        ),
        migrations.RemoveField(
            model_name='lavoratore',
            name='mansione',
        ),
        migrations.RemoveField(
            model_name='lavoratore',
            name='mansione_1',
        ),
        migrations.RemoveField(
            model_name='lavoratore',
            name='mansione_2',
        ),
        migrations.RemoveField(
            model_name='lavoratore',
            name='mansione_3',
        ),
    ]
