# Generated by Django 4.1.5 on 2024-01-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0062_remove_lavoratore_attivita_svolta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoratore',
            name='assunzione',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='busta_paga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='qualifica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
