# Generated by Django 4.1.5 on 2024-03-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0063_alter_lavoratore_assunzione_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idoneita',
            old_name='calzature',
            new_name='calzature_plantare',
        ),
        migrations.AlterField(
            model_name='formazione',
            name='antincendio_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='art37_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='aspp_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='autogru_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='carrello_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='dirigente_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='dumper_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='ept_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='gru_autocarro_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='imbracatore_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='ple_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='ponteggiatore_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='preposto_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='primo_soccorso_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='rls_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='rullo_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='sollevatore_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formazione',
            name='spazi_confinati_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='idoneita',
            name='idoneita_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
    ]
