# Generated by Django 4.1.5 on 2024-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0064_rename_calzature_idoneita_calzature_plantare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='calzature_leggere',
            field=models.BooleanField(default=False),
        ),
    ]
