# Generated by Django 4.1.5 on 2024-04-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0065_idoneita_calzature_leggere'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='altezza',
            field=models.BooleanField(default=False, verbose_name='Lavori in altezza'),
        ),
    ]
