# Generated by Django 4.1.5 on 2024-06-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0067_alter_formazione_antincendio_ck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='flessioni_rachide',
            field=models.BooleanField(default=False),
        ),
    ]
