# Generated by Django 4.1.5 on 2024-09-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0068_idoneita_flessioni_rachide'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='sollecitazioni_spalla_sinistra',
            field=models.BooleanField(default=False),
        ),
    ]
