# Generated by Django 4.1.5 on 2024-11-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0069_idoneita_sollecitazioni_spalla_sinistra'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='mmc_ck',
            field=models.CharField(blank=True, choices=[(None, 'ok_np'), ('table-warning', 'scade'), ('table-danger', 'scaduto'), ('es-aspp', 'esonero aspp'), ('es-prep', 'esonero preposto')], default='ok_np', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='mmc_dc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formazione',
            name='mmt',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
