# Generated by Django 4.1.5 on 2024-11-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0070_formazione_mmc_ck_formazione_mmc_dc_formazione_mmt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formazione',
            old_name='mmt',
            new_name='mmc',
        ),
    ]
