# Generated by Django 4.1.5 on 2025-01-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0071_rename_mmt_formazione_mmc'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='calzature_plantare_morbido',
            field=models.BooleanField(default=False),
        ),
    ]
