# Generated by Django 4.1.5 on 2025-01-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0072_idoneita_calzature_plantare_morbido'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='sbalzi_termici',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idoneita',
            name='rumore50',
            field=models.BooleanField(default=False, verbose_name='Esposizione giornaliera rumore < 50%'),
        ),
        migrations.AlterField(
            model_name='idoneita',
            name='temperature',
            field=models.BooleanField(default=False, verbose_name='Temperature elevate'),
        ),
    ]
