# Generated by Django 4.1.5 on 2025-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0073_idoneita_sbalzi_termici_alter_idoneita_rumore50_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoratore',
            name='assunzione',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='busta_paga',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='qualifica',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
