# Generated by Django 4.1.5 on 2025-08-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0074_alter_lavoratore_assunzione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavoratore',
            name='consegnato_ap',
            field=models.BooleanField(blank=True, null=True, verbose_name='Badge AP consegnato'),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='scadenza_ap',
            field=models.IntegerField(blank=True, null=True, verbose_name='Scadenza badge AP'),
        ),
    ]
