# Generated by Django 4.1.5 on 2025-08-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0075_lavoratore_consegnato_ap_lavoratore_scadenza_ap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoratore',
            name='citta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Città'),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='cognome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
