# Generated by Django 4.1.5 on 2025-08-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0076_alter_lavoratore_citta_alter_lavoratore_cognome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoratore',
            name='consegnato_ap',
            field=models.BooleanField(blank=True, null=True, verbose_name='Badge AdSP consegnato'),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='scadenza_ap',
            field=models.IntegerField(blank=True, null=True, verbose_name='Badge AdSP scadenza'),
        ),
    ]
