# Generated by Django 4.1.5 on 2025-08-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0077_alter_lavoratore_consegnato_ap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idoneita_Revisione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('revisione', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Idoneità - Revisione',
                'verbose_name_plural': 'Idoneità - Revisione',
            },
        ),
        migrations.DeleteModel(
            name='DPI',
        ),
    ]
