# Generated by Django 4.1.5 on 2025-09-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0078_idoneita_revisione_delete_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoneita',
            name='martello_pneumatico',
            field=models.BooleanField(default=False),
        ),
    ]
